---
title: "Pred2Project_EDA"
author: "Rachel Rosenberg"
date: "2/13/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = '~/420 - Predictive II/Aggregated Data')
library(tidyverse)
library(readxl)
library(plyr)
library(dplyr)
```

## Import Data
```{r}
#Import the Food Inspection-related data

Garbage_Carts <- read_csv("~/z/Grocery Stores/PA Project/Aggregated Data/311_Service_Requests_-_Garbage_Carts.csv")
Sanitation <- read_csv("~/z/Grocery Stores/PA Project/Aggregated Data/311_Service_Requests_-_Sanitation_Code_Complaints.csv")
Business_Licenses <- read_csv("~/z/Grocery Stores/PA Project/Aggregated Data/Business_Licenses.csv")
Food_Inspections <- read_csv("~/z/Grocery Stores/PA Project/Aggregated Data/Food_Inspections.csv")
Affordable_Housing <- read_csv("~/z/Grocery Stores/PA Project/Aggregated Data/Affordable_Rental_Housing_Developments.csv")

```
```{r}
library(lubridate)

#Create variable for month of inspection
Food_Inspections$inspection_month <- month(as.POSIXlt(Food_Inspections$`Inspection Date`, format="%m/%d/%Y"))

#Filter Food Inspection Data for usable columns
Food_Inspections_filtered <- Food_Inspections[,c(1:2,4,5,6,10:13,18)]

#Create Binary Classifyer for Pass/Fail (will need to adjust later)
Food_Inspections_filtered$Results_Numeric <- ifelse(Food_Inspections_filtered$Results =="Fail", 0, 1)
  
#filter for usable business license info
License_Desc <- Business_Licenses[,c(2,11,16)]

#filter for usable sanitation info then aggregate for each ward
Sanitation_filtered <- Sanitation[,c(4,11)]
Sanitation_filtered <- aggregate(`Service Request Number` ~ Ward, Sanitation_filtered, function(x) length(unique(x)))
colnames(Sanitation_filtered)[2] <- "Num_Sanitation_Requests"

#filter for usable garbage info then aggregate for each ward
Garbage_filtered <- Garbage_Carts[,c(4,13)]
Garbage_filtered <- aggregate(`Service Request Number` ~ Ward, Garbage_filtered, function(x) length(unique(x)))
colnames(Garbage_filtered)[2] <- "Num_Garbage_Requests"

Affordable_Housing_by_ZIP <- aggregate(Affordable_Housing$Units, by=list(Category=Affordable_Housing$`Zip Code`), FUN=sum)
colnames(Affordable_Housing_by_ZIP) <- c("Zip", "Affordable_Housing_Units")
```

#join data together
```{r}

ModelData <- merge(Food_Inspections_filtered, License_Desc, by.x = "License #", by.y = "LICENSE ID")
ModelData <- merge(ModelData, Sanitation_filtered, by.x = "WARD", by.y = "Ward")
ModelData <- merge(ModelData, Garbage_filtered , by.x = "WARD", by.y = "Ward")
ModelData <- merge(ModelData, Affordable_Housing_by_ZIP , by.x = "Zip", by.y = "Zip")




```

#Create linear model
```{r}

linear_model <- glm(ModelData$Results_Numeric ~ factor(ModelData$WARD) , family=binomial(link="logit"))

linear_model <- glm(ModelData$Results_Numeric ~  factor(ModelData$inspection_month) +  ModelData$Num_Sanitation_Requests  + ModelData$Num_Garbage_Requests + ModelData$Affordable_Housing_Units)
summary(linear_model)


```
















#Everything below here is old



## Join Health data and neighborhoods
```{r}
colnames(ZIPtoCA) <- c("ChicagoCA", "ZIPCode", "2010Pop")
health <- merge(health, ZIPtoCA, by.x = "Community.Area", by.y = "ChicagoCA")
health <- merge(health, ZIP, by.x = "ZIPCode", by.y = "Zip Code")
health <- health[ , c(1:4, 18, 5:17, 18:32)] # reorder columns

write.csv(health, file = "~/420 - Predictive II/Aggregated Data/healthWithZIPSandCAs.csv")
```

## Create full matrix of predictors
```{r}
allPreds <- health
names(allPreds)
head(allPreds)
head(grocery)

# Merge in park_areas
allPreds <- merge(allPreds, park_areas, by.x = "ZIPCode", by.y = "ZIP")

# Merge in num_of_parks
allPreds <- merge(allPreds, num_of_parks, by.x = "ZIPCode", by.y = "ZIP")

# Merge in liquor
allPreds <- merge(allPreds, liquor, by.x = "ZIPCode", by.y = "Zip Code")

# Merge in grocery
allPreds <- merge(allPreds, grocery, by.x = "Neighborhood", by.y = "Neighborhood")

# write.csv(allPreds, file = "~/420 - Predictive II/Aggregated Data/allPredictors.csv")
```

## Build linear model
```{r}
colnames(allPreds)[colnames(allPreds)=="Liquor Licenses"] <- "Liquor.Licenses"
colnames(allPreds)[colnames(allPreds)=="Grocery Stores"] <- "Grocery.Stores"


names(allPreds)
fit_lm <- lm(Diabetes.related ~ Cancer..All.Sites. + Birth.Rate + Below.Poverty.Level + Parks + Liquor.Licenses + Grocery.Stores, data = allPreds)
summary(fit_lm)

LinearPreds <- cbind(allPreds$Diabetes.related, allPreds$Cancer..All.Sites., allPreds$Birth.Rate, allPreds$Below.Poverty.Level, allPreds$Parks, allPreds$Liquor.Licenses, allPreds$Grocery.Stores)

```

## Fit nnet
```{r}
#standardize all predictors
allPreds1<-allPreds
dropcols <- c("Childhood.Blood.Lead.Level.Screening","Childhood.Lead.Poisoning", "Gonorrhea.in.Females", "Gonorrhea.in.Males")
allPreds1 <- allPreds1[ , !(names(allPreds1) %in% dropcols)]
allPreds1<-sapply(allPreds1[5:33],function(x) (x-mean(x))/sd(x))

```

#Function to make a CV index partition
```{r}
CVInd <- function(n,K) {  #n is sample size; K is number of parts; returns K-length list of indices for each part
  m<-floor(n/K)  #approximate size of each part
  r<-n-m*K  
  I<-sample(n,n)  #random reordering of the indices
  Ind<-list()  #will be list of indices for all K parts
  length(Ind)<-K 
  for (k in 1:K) {
    if (k <= r) kpart <- ((m+1)*(k-1)+1):((m+1)*k)   
    else kpart<-((m+1)*r+m*(k-r-1)+1):((m+1)*r+m*(k-r)) 
    Ind[[k]] <- I[kpart]  #indices for kth part of data
    }
    Ind
}
```

#Check R squared
```{r}
library(nnet)

out<-nnet(Diabetes.related ~ . -Diabetes.related, allPreds1, linout=T, skip=F, size=10,decay=.1,maxit=1000,trace=F)
y <- allPreds1[,12]
yhat<-as.numeric(predict(out))
e<-y-yhat
c(sd(y),sd(e))
1-var(e)/var(y)


```

#Check ALE plots
```{r}
library(ALEPlot)
yhat <- function(X.model, newdata) as.numeric(predict(X.model, newdata))
par(mfrow=c(2,4))

for (j in 1:28)  {ALEPlot(allPreds1[], out, pred.fun=yhat, J=j, K=50, NA.plot = TRUE)
  rug(allPreds1[,j+1]) }  ## This creates main effect ALE plots for all predictors
par(mfrow=c(1,1))
```




## Fit decision tree
```{r}
library(rpart)

control    <-  rpart.control(minbucket  =  5,  cp  =  0.000000001,  xval  =  10,  maxsurrogate  =  0,  usesurrogate = 0) # choose cp as small as you can. This cp corresponds to the largest tree to grow.
out  <- rpart(Diabetes.related ~ . -Diabetes.related, data = allPreds[,5:37], method = 'anova', control = control)

plotcp(out)

bestcp  <-  out$cptable[which.min(out$cptable[,"xerror"]),"CP"]  #  cp  parameter  with  minimal
bestcp

```
```{r}
out1 <- prune(out, cp= .004)
plot(out1); text(out1)
```


```{r}
y <- allPreds$Diabetes.related
yhat<-as.numeric(predict(out1))
e<-y-yhat
c(sd(y),sd(e))
1-var(e)/var(y)
```


```{r}
printcp(out1)


rpart(formula = Diabetes.related ~ ., data = allPreds, method = "anova",     control = control)

out1$variable.importance

plot(yhat,e)
```

