---
title: "Pred2Project_EDA"
author: "Rachel Rosenberg"
date: "2/13/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = '~/420 - Predictive II/Aggregated Data')
library(tidyverse)
library(readxl)
library(plyr)
library(dplyr)
library(rpart)
library(nnet)

```

## Import Data
```{r}
park_areas <- read_excel("~/420 - Predictive II/Aggregated Data/Park Areas by ZIP.xlsx")
ZIP <- read_excel("~/420 - Predictive II/Aggregated Data/ZIP to Neighborhood.xlsx")
num_of_parks <- read_excel("~/420 - Predictive II/Aggregated Data/Number of Parks by ZIP.xlsx")
liquor <- read_excel("~/420 - Predictive II/Aggregated Data/Liquor Licenses by ZIP.xlsx")
grocery <- read_excel("~/420 - Predictive II/Aggregated Data/Grocery Stores by Neighborhood.xlsx")
health <- read.csv("~/420 - Predictive II/Aggregated Data/Public_Health_Statistics-_Selected_public_health_indicators_by_Chicago_community_area.csv")
ZIPtoCA <- read_excel("~/420 - Predictive II/Aggregated Data/ZIPtoCA.xlsx")
```

## Join Health data and neighborhoods
```{r}
colnames(ZIPtoCA) <- c("ChicagoCA", "ZIPCode", "2010Pop")
health <- merge(health, ZIPtoCA, by.x = "Community.Area", by.y = "ChicagoCA")
health <- merge(health, ZIP, by.x = "ZIPCode", by.y = "Zip Code")
health <- health[ , c(1:4, 18, 5:17, 18:32)] # reorder columns

write.csv(health, file = "~/420 - Predictive II/Aggregated Data/healthWithZIPSandCAs.csv")
```

## Create full matrix of predictors
```{r}
allPreds <- health
names(allPreds)
head(allPreds)
head(grocery)

# Merge in park_areas
allPreds <- merge(allPreds, park_areas, by.x = "ZIPCode", by.y = "ZIP")

# Merge in num_of_parks
allPreds <- merge(allPreds, num_of_parks, by.x = "ZIPCode", by.y = "ZIP")

# Merge in liquor
allPreds <- merge(allPreds, liquor, by.x = "ZIPCode", by.y = "Zip Code")

# Merge in grocery
allPreds <- merge(allPreds, grocery, by.x = "Neighborhood", by.y = "Neighborhood")

nrow(allPreds)

# write.csv(allPreds, file = "~/420 - Predictive II/Aggregated Data/allPredictors.csv")
```

## Build linear model
```{r}
names(allPreds)
fit_lm <- lm(Diabetes.related ~ Cancer..All.Sites. + Birth.Rate + Below.Poverty.Level + Parks + `Liquor Licenses` + `Grocery Stores`, data = allPreds)
summary(fit_lm)
```

## Define CVInd function
```{r}
CVInd <- function(n,K) {  #n is sample size; K is number of parts; returns K-length list of indices for each part
   m <- floor(n/K)  #approximate size of each part
   r <- n - m*K  
   I <- sample(n, n)  #random reordering of the indices
   Ind <- list()  #will be list of indices for all K parts
   length(Ind) <- K
   for (k in 1:K) {
      if (k <= r) kpart <- ((m+1)*(k-1)+1):((m+1)*k)  
         else kpart<-((m+1)*r+m*(k-r-1)+1):((m+1)*r+m*(k-r))
      Ind[[k]] <- I[kpart]  #indices for kth part of data
   }
   Ind
}
```

## Fit nnet
```{r, cache=TRUE}

```

## Fit decision tree
```{r}
allPredsforTree <- allPreds[ , -which(names(allPreds) %in% c("Community.Area.Name", "Neighborhood", "ZIPCode", "Community.Area"))]
allPredsforTree$Gonorrhea.in.Males <- as.numeric(allPredsforTree$Gonorrhea.in.Males)
# allPredsforTree$Community.Area <- as.factor(allPredsforTree$Community.Area) # this introduces too many CAs
head(allPredsforTree)

## Use plot to choose the best Cp and minbucket values
control <- rpart.control(minbucket = 10, cp = 0.0001, maxsurrogate = 0, usesurrogate = 0, xval = 10)
tree <- rpart(Diabetes.related ~ ., allPredsforTree, method = "anova", control = control)
plotcp(tree)  #plot of CV r^2 vs. size
#printcp(tree)  #same info is in CRT.tr$cptable
```

```{r}
## prune back to optimal size, according to plot of CV 1-r^2
tree <- prune(tree, cp=0.001)  #approximately the best size pruned tree
tree$variable.importance # get variable importance
tree$cptable[nrow(tree$cptable), ] #shows training and CV 1-r^2, and other things
par(cex=.9); plot(tree, uniform=F); text(tree, use.n = T); par(cex=1) # plot tree 

## Check accuracy
yhat <- predict(tree)
e <- allPreds$Diabetes.related - yhat
c(1-var(e)/var(allPreds$Diabetes.related), 1 - tree$cptable[nrow(tree$cptable),3]) #check to see training r^2 agrees with what is in cptable

## Plot
plot(yhat, e)
```


